### PR TITLE
Get `secd` and `trustd` to build

### PR DESCRIPTION
**Pull request by facekapow**
Depends on darlinghq/darling-libxpc#3 and darlinghq/darling#731.

From my preliminary tests, they're building and installing, and `trustd` seems to be launching properly, but it seems that it's not working properly. Trying to run `curl`, it succeeds in finding `com.apple.trustd`, but it eventually freezes on the syscall waiting for trustd to respond. I can't seem to get secd to start, though.

Edit: upon further investigation, it seems that the problem lies with somewhere in the inter-process communication used to communicate with trustd. Either trustd is listening for messages incorrectly or Mach messaging isn't passing the message to trustd, because it looks like `xpc_send` is doing its job correctly in the client.

Edit 2: Actually, `xpc_send` is failing silently because `xpc_connection_send_message_with_reply` ignores `xpc_send`'s return code. `mach_msg_send` is actually returning `KERN_INVALID_HOST`. I'll debug this more tomorrow.

### CODE REVIEW

**Comment by bugaevc** [comment]
> `mach_msg_send` is actually returning `KERN_INVALID_HOST`

I don't think that's an error code that `mach_msg()` can return. MIG routines such as `host_reboot()` can, if you pass them an invalid host port. But the Mach messaging layer doesn't know anything about the meaning of ports, or what a host is.

**Comment by facekapow** [comment]
Well, the actual error code is just `22`, which I assumed was `KERN_INVALID_HOST` since that was the definition I found in `kern_return.h`. `dmesg` and `xtrace` aren't much help either:

dmesg:
```
<7>[ 1644.372545] Darling TID 22978 (PID 22978) says: libxpc: xpc_connection_resume(): connection=0x7fb2c341dde0, internally 0x7fb2c341ddf0
...
<7>[ 1644.372856] Darling TID 22978 (PID 22978) says: libxpc: I'm waiting (blocking) for reply
...
<7>[ 1644.372958] Darling TID 22982 (PID 22978) says: libxpc: Recv queue 0x7fb2c3437ac0 works! #1
...
<7>[ 1644.372974] Darling TID 22982 (PID 22978) says: libxpc: Recv queue works! #2
...
<7>[ 1644.372997] Darling TID 22982 (PID 22978) says: libxpc: xpc_send(): connection=0x7fb2c341dde0, message=0x7fb2c340a810 (type=1), id=2
...
<7>[ 1644.373003] Darling TID 22982 (PID 22978) says: libxpc: obj type is 1
...
<7>[ 1644.373010] Darling TID 22982 (PID 22978) says: libxpc: packing message
...
<7>[ 1644.373016] Darling TID 22982 (PID 22978) says: libxpc: 1 nvl = 0x7fb2c3437490
...
<7>[ 1644.373020] Darling TID 22982 (PID 22978) says: libxpc: nv = 0x7fb2c3437490
...
<7>[ 1644.373083] Darling TID 22982 (PID 22978) says: libxpc: 1 nvl = 0x7fb2c3430cf0
...
<7>[ 1644.373085] Darling TID 22982 (PID 22978) says: libxpc: nv = 0x7fb2c3430cf0
...
<7>[ 1644.373105] Darling TID 22982 (PID 22978) says: libxpc: send failed, kr=22
```

xtrace:
```
[117] mach_msg_trap(0x7fffffdfc228, MACH_SEND_MSG|MACH_RCV_MSG, 188, 108, port 1543, 0, port 0)
[117]         {remote = copy send 1799, local = make send-once 1543, id = 404}, 164 bytes of inline data
[117]         job::look_up2(copy send 1799, [;1m"com.apple.trustd", 0, [132, 7, 0, 0, 166, 255, 255, 0, 0, 255, 0, 0, 0, 0, 0, 0], 0)
[117]     mach_msg_trap() -> KERN_SUCCESS
[117]         {local = move send-once 1543, complex, id = 504}, move send 4355, 0 bytes of inline data
[117]         job::look_up2() -> move send 4355, {0, 0, 0, 0, 0, 0, 0, 0} 
[117] _kernelrpc_mach_vm_map_trap(...)[117] task_self_trap() -> port right 259
[117] mmap(0x1000, 25165824, PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE, -1, 0) -> 0x7ffff2ec9000
[117] munmap(0x7ffff2ec9000, 25165824) -> 0
[117] mmap(0x1000, 27262976, PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE, -1, 0) -> 0x7ffff2cc9000
[117] munmap(0x7ffff2cc9000, 1273856) -> 0
[117] munmap(0x7ffff4600000, 823296) -> 0
 -> 0x
[117] guarded_kqueue_np(0x7fffffdfad88, 3)[117] getrlimit(4104, 0x7fffffdfaa28) -> 0
[117] mmap(NULL, 8388600, PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE, -1, 0) -> 0x7ffff2600000
 -> 0x

[117] kevent64(4, 0x7ffff682dbe0, 1, NULL, 0, 0, NULL)[117] thread_selfid() -> 117
 -> 0x

[117] bsdthread_create(0x7ffff6801de0, 0x7ffff684c0a0, 0x10000, NULL, 201328895)[119] thread_self_trap() -> port right 4611
 -> 140737305415680
[119][117]  thread_selfidkevent64()(4, 0x7fffffdfb008, 1, 0x7fffffdfaf20, 1, 0, NULL) -> [117] 119
thread_selfid() -> 0x

[119][117]  __pthread_sigmaskwrite(1, 0x7ffff5188cec, NULL)(5, 0x7fffffdfab30, 8) -> 0
 -> 8
 -> 0x

[119] _kernelrpc_mach_vm_allocate_trap(...)[119] task_self_trap() -> port right 259
[117][119]  workq_kernreturntask_self_trap(32, NULL, 1, 65537)() -> port right 259
[119] mmap(0x1000, 16384, PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE, -1, 0) -> 0x7ffff46c5000
 -> 0x
[120] thread_self_trap()[119] ->  port right 4867
_kernelrpc_mach_port_allocate_trap(task 259, MACH_PORT_RIGHT_PORT_SET) -> 0
[120] ->  port right 5123
thread_selfid()[119] ->  0x

kevent64(4, 0x7ffff51868c8, 1, 0x7ffff51867e0, 1, 0, NULL)[117] [120][119]  mach_msg_trapworkq_kernreturn(0x7fffffdfc688, MACH_SEND_MSG|MACH_RCV_MSG, 40, 48, port 1543, 0, port 0)(32, NULL, 1, 65537)thread_selfid
()[117] ->   119
       {[119]remote = copy send 259,  local = make send-once 1543, id = 3418}fcntl, 16 bytes of inline data
(7, 2, 1)[117]   ->   0
 [121]    ->  thread_self_trap ()0x

task::semaphore_create(copy send 259[119],  0, _kernelrpc_mach_port_move_member_trap0(task 259, port right 4099, port set 5123) -> )
port right 5379
 ->  -> KERN_SUCCESS
[121]0
 [119]thread_selfid ()kevent64 -> (4, 0x7ffff5187ec8, 0, 0x7ffff5187ef8, 1, 0, NULL)0x

[119][117]  [121] thread_selfid  () workq_kernreturn  -> (32, NULL, 1, 65537)119
mach_msg_trap()[119]  -> readKERN_SUCCESS
(5, 0x7ffff5187a60, 8)[117]   ->   8
   ->   0x

 [119]{ local = move send-once 1543, complex, kevent64id = 3518}(4, 0x7ffff5187ec8, 0, 0x7ffff5187ef8, 1, 0, NULL), move send 5635, 0 bytes of inline data
[117]        [122]  thread_self_traptask::semaphore_create() -> ()move send 5635[120]  
 -> workq_kernreturn[117](4, NULL, 0, 0)port right 5891
  -> semaphore_wait_trap[122](...)0
 thread_selfid[121]()  -> kevent64(4, 0x7ffff46c1d68, 1, 0x7ffff46c1c80, 1, 0, NULL)122
[121] [122]thread_selfid ()workq_kernreturn -> (4, NULL, 0, 0)0x

 -> 0x

[121] _kernelrpc_mach_vm_allocate_trap(...)[121] task_self_trap() -> port right 259
[121] task_self_trap() -> port right 259
[121] mmap(0x3, 4096, PROT_READ|PROT_WRITE, MAP_ANON|MAP_PRIVATE, -1, 0) -> 0x7ffff5177000
 -> 0x
[121] socket(1, 2, 0) -> 8
[121] fcntl(8, 2, 1) -> 0
[121] connect(8, 0x7ffff46c16a8, 106) -> ECONNREFUSED
[121] close(8)[121] kevent64(4, 0x7ffff46c1510, 2, NULL, 0, 0, NULL)[121] thread_selfid() -> 121
 -> 0x

 -> 0x

[121] _kernelrpc_mach_vm_deallocate_trap(...)[121] task_self_trap() -> port right 259
[121] munmap(0x7ffff5177000, 4096) -> 0
 -> 0x
[121] workq_kernreturn(4, NULL, 0, 0)
```
(for some reason, probably from multiple threads trying to print at the same time, my xtrace output gets jumbled at the end)

**Comment by facekapow** [comment]
Ok, LLDB was throwing me off; turns out that it's not `mach_msg` that was returning 22, it's `nvlist_pack_buffer`, which assigns it to errno and `xpc_pipe_send` returns it. `nvlist_pack_buffer`, in turn, gets it from `nvl_error` in the provided `nvlist`. Still trying to figure out where the `22` came from.

**Comment by bugaevc** [comment]
It's a catch 22 😂

**Comment by LubosD** [comment]
22 is most likely EINVAL in this case.

**Comment by facekapow** [comment]
So I added a few more `debugf`s to `xpc2nv` (because LLDB was being *very* unhelpful), and it seems that the error is happening after processing the first item in the "ExtendedKeyUsage" array in the "policies" dictionary:

```
<7>[  361.714949] Darling TID 19054 (PID 19043) says: libxpc: processing dict entry: ExtendedKeyUsage
...
<7>[  361.714952] Darling TID 19054 (PID 19043) says: libxpc: processing array entry: 0
...
<7>[  361.714956] Darling TID 19054 (PID 19043) says: libxpc: nv->nvl_error = 22
```

Before that, `nv->nvl_error` is always `0`.

**Comment by facekapow** [comment]
Ah okay, finally. The `22` *is* in fact `EINVAL` and it's coming from `nvpair_createv_binary`. The reason is that the function checks to make sure that `value` isn't NULL and that `size` is greater than `0`, but the first entry of ExtendedKeyUsage has `0` length:
```
3 : <CFString 0x7ffff763f418 [0x7ffff7ccce00]>{contents = "ExtendedKeyUsage"} = <CFArray 0x7ffd1ec26020 [0x7ffff7ccce00]>{type = mutable-small, count = 5, values = (
	0 : <CFData 0x7ffd1ec2cc20 [0x7ffff7ccce00]>{length = 0, capacity = 0, bytes = 0x}
	1 : <CFData 0x7ffd1ec1cd20 [0x7ffff7ccce00]>{length = 4, capacity = 4, bytes = 0x551d2500}
	2 : <CFData 0x7ffd1ec1b5b0 [0x7ffff7ccce00]>{length = 8, capacity = 8, bytes = 0x2b06010505070301}
	3 : <CFData 0x7ffd1ec18d70 [0x7ffff7ccce00]>{length = 10, capacity = 10, bytes = 0x2b0601040182370a0303}
	4 : <CFData 0x7ffd1ec190c0 [0x7ffff7ccce00]>{length = 9, capacity = 9, bytes = 0x6086480186f8420401}
)}
```
Is there an actual reason why `nvpair_createv_binary` (and its complement, `nvpair_unpack_binary`) needs to check if the size isn't zero? I removed the checks in my local copy and it seems to build and run just fine.

With that out of the way, the next error comes from:
```
Assertion failed: (level < 3), function nvlist_xndescriptors, file ~/git/darling/src/external/libxpc/subr_nvlist.c, line 669.
Abort trap: 6 (core dumped)
```
Which seems to be because of an unsupported number of nested dictionaries/arrays/nvlists.

**Comment by bugaevc** [comment]
See, that's why I'm saying our current libxpc desperately needs to be rewritten. NextBSD people wanted to have it use nvlist for consistency with other BSD stuff (I guess), but it's a poor fit for us.

**Comment by facekapow** [comment]
Did XPC used to work? Because after removing the asserts, cURL sends the message successfully, and trustd receives the connection, but not the message. My guess is that the message that initiated the connection wasn't stored to be processed on `xpc_connection_resume` (but this is just a guess, I haven't looked at the libdispatch code that handles the message queue yet),.

Also, I ask that question ("did XPC used to work?") more generally because I tried using `syslog` to see messages from trustd and it hung just like cURL after trying to connect to `"com.apple.system.logger"` and sending an initial message.

What's odd is that when I run `xtrace` on `curl` and `security`, they *seem* to succeed in communicating and sending messages back and forth with `"com.apple.system.notification_center"`.

---

Also, I agree, @bugaevc; libxpc does need a rewrite to conform with macOS's libxpc behavior (granted, I have spent *very* little time messing with libxpc, so this doesn't mean much 😄), but I'd still like to try to make messaging work with the current version, since my focus right now is getting trustd to talk to cURL.

**Comment by bugaevc** [comment]
> Did XPC used to work?

The answer is ["a little"](https://github.com/darlinghq/darling-libxpc/commit/4437a46ee1b8fa0bdc1286ea84804bd0fcd1ba6d#diff-c9ce120d2477774659bdf664c3bf174c).

> My guess is that the message that initiated the connection wasn't stored to be processed on `xpc_connection_resume` (but this is just a guess, I haven't looked at the libdispatch code that handles the message queue yet),.

No, that's not it. libdispatch is not involved in actually processing XPC messages, and the first message seems to be getting queued properly.

> What's odd is that when I run `xtrace` on `curl` and `security`, they seem to succeed in communicating and sending messages back and forth with `"com.apple.system.notification_center".`

But that's MIG, not XPC.

**Comment by facekapow** [comment]
It turns out that the test for `if (peer->xc_handler)` was running before the async handler for a new peer connection finished running so there was no `peer->xc_handler` set yet. I've opened up a PR in libxpc (darlinghq/darling-libxpc#4) that includes a fix for this plus it removes the other two unnecessary checks from before.

Now curl receives `Unimplemented syscall (169)` which, according to [this](https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/kern/syscalls.master#L257), is "csops", code-signing operations.

**Comment by LubosD** [comment]
@facekapow The sources for csops are available (in XNU), but I'm not very sure what it's _precisely_ doing, because the code comments are rather cryptic. And because it works with things such as "vnode", I do need to understand the code fully in order to do a port to Linux.

But I assume it's all about checking Mach-O file signatures, so you could maybe add a dummy implementation into `src/kernel/emulation/linux` (which is in user space) just to make it happy?

**Comment by facekapow** [comment]
I've opened up darlinghq/darling#732 for the dummy implementation as well as darlinghq/darling-libxpc#5 (trustd was segfaulting in libxpc because of a requested key not being present in the dictionary).

With all that in place, cURL now reports:

```
Darling [~]$ curl https://www.example.com
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
...And we're back to where we started! 😆

I'm going to keep debugging this, but my initial guess is that trustd isn't finding our certificates.

**Comment by LubosD** [comment]
If trustd looks for certs in our keychain, then it's simple, because we don't have any :-D

**Comment by facekapow** [comment]
trustd was silently erroring because libxpc wasn't working properly. I've opened up darlinghq/darling-libxpc#6 to fix this.

The next hurdle was `_CFXPCCreateCFObjectFromXPCObject` not being implemented. I've opened up darlinghq/darling-corefoundation#3 to (partially) implement it.

Now trustd progresses to:
```
Darling [~]$ curl https://www.example.com
DARLING CRYPTO STUB: cc_size ccder_decode_rsa_pub_x509_n(const uint8_t *, const uint8_t *)
                                                                                          DARLING CRYPTO STUB: cc_size ccder_decode_rsa_pub_x509_n(const uint8_t *, const uint8_t *)
                                               DARLING CRYPTO STUB: cc_size ccder_decode_rsa_pub_x509_n(const uint8_t *, const uint8_t *)
    DARLING CRYPTO STUB: cc_size ccder_decode_rsa_pub_x509_n(const uint8_t *, const uint8_t *)
                                                                                              Unimplemented syscall (483)
                                                                                                                         Unimplemented syscall (483)
               Unimplemented syscall (483)
                                          Assertion failed: (isRealized()), function hasCxxDtor, file /home/me/git/darling/src/external/objc4/runtime/objc-runtime-new.h, line 1137.
```
(the command is `curl`, but the messages are from `trustd`)

So now it seems to be missing:
  1. `ccder_decode_rsa_pub_x509_n`. Something else I'll implement in darlinghq/darling-corecrypto#6
  2. Syscall 483. Seems to be `csrctl`, which I *believe* is System Integrity Protection (SIP). If it is, then we should be able to just return a value indicating unrestricted access (i.e. no SIP)
  3. Some error in the Objective-C runtime? Might be a non-issue if it's related to the previous errors.

**Comment by bugaevc** [comment]
> Some error in the Objective-C runtime?

Oh, that's what happens when you send a message to (what appears to be) an object with an invalid (maybe Nil) Isa.

**Comment by facekapow** [comment]
It looks like I've implemented all the necessary stuff for certificate verification in CoreCrypto, and I implemented syscall 483 locally (that returns a value indicating unrestricted access), which I can open up a PR for later.

It seems that the Objective-C error is coming from trying to destroy a CFMachPort as an Objective-C object and it has an "unrealized" ISA (and CFRuntime thinks its an Objective-C object because its `__cfisa` is non-zero). Not exactly sure what this means; will keep debugging.

Edit: from what I can tell, it seems that the error occurs because CFMachPort is Toll-Free Bridged with NSMachPort in `_CFRuntimeBridgeClasses` which uses `objc_getFutureClass`, but `NSMachPort` doesn't become realized:
```
(lldb) p objc_getClass("NSMachPort")
(Class) $21 = nil
(lldb) p objc_getFutureClass("NSMachPort")
(Class) $22 = 0x00007fcc90c00750
(lldb)
```

**Comment by bugaevc** [comment]
> and CFRuntime thinks its an Objective-C object because its `__cfisa` is non-zero

That's not enough for it to be considered not a CF object; its isa also has to not-match the corresponding CF class. See https://github.com/darlinghq/darling-corefoundation/blob/master/include/CoreFoundation/CFInternal.h#L603

**Comment by facekapow** [comment]
That's actually not the check being used to see if the pointer is an Objective-C object, [this](https://github.com/darlinghq/darling-corefoundation/blob/97aed63cd00e3d8bd4719199356c8de818960497/CFRuntime.c#L1700) is.

Btw, if the function you pointed out were being used, this wouldn't be an issue because the first lines of it check for tagged pointers and LLDB says:
```
(lldb) p _objc_taggedPointersEnabled()
(bool) $41 = true
(lldb) p _objc_isTaggedPointer(cf)
(bool) $42 = false
(lldb)
```
...on the object being attempted to be destroyed.

**Comment by bugaevc** [comment]
> That's actually not the check being used to see if the pointer is an Objective-C object, this is.

You're right! I didn't consider unrealized classes when I wrote that part. Please check if this fixed it:

```diff
- 	    Boolean isValidObjCObject = ((CFRuntimeBase *) cf)->_cfisa != 0;
+ 	    Class isa = (Class) ((CFRuntimeBase *) cf)->_cfisa;
+ 	    Boolean isValidObjCObject = isa != NULL && !_class_isFutureClass(isa);
```

> Btw, if the function you pointed out were being used

But it cannot be used here, specifically because we want TFBed objects to go through objc runtime here, unlike in other places.

> because the first lines of it check for tagged pointers and LLDB says

Huh? It's not a tagged pointer, so what?

Also, please stop using edits to add meaningful content. Those of us who rely on email notifications to read GitHub conversations miss all the things you add. Use edits to fixes typos and such, and don't shy away from writing a new message when you have something to add.

**Comment by facekapow** [comment]
> Please check if this fixed it

Yep, that did the trick. 👍

> Huh? It's not a tagged pointer, so what?

Sorry, I misunderstood what tagged pointers are (in case it's not obvious, I know next to nothing about Objective-C and didn't bother to lookup what tagged pointers are before posting that).

> Also, please stop using edits to add meaningful content. Those of us who rely on email notifications to read GitHub conversations miss all the things you add. Use edits to fixes typos and such, and don't shy away from writing a new message when you have something to add.

Sorry, noted. 😄

**Comment by facekapow** [comment]
With that fix in place, cURL is now back to `curl: (60) SSL certificate problem: Invalid certificate chain`. 😕

**Comment by bugaevc** [comment]
> in case it's not obvious, I know next to nothing about Objective-C

Heh, that's alright. I didn't know objc at all when I started hacking on Darling 😀

**Comment by LubosD** [comment]
> With that fix in place, cURL is now back to `curl: (60) SSL certificate problem: Invalid certificate chain`.

I know I've said it before, but the keychain files don't yet exist in Darling. So you should entertain the possibility that it's just that :-D

Here are the default keychain files from macOS 10.15: [keychains.tar.gz](https://github.com/darlinghq/darling-security/files/4483464/keychains.tar.gz) This should be unpacked in `/`.

**Comment by bugaevc** [comment]
> Yep, that did the trick. +1

...but that doesn't work (as in crashes) when isa is tagged, hmm. Try this:
```diff
--- a/CFRuntime.c
+++ b/CFRuntime.c
@@ -1697,7 +1697,11 @@ static void _CFRelease(CFTypeRef cf) {
        }
 
        {
-           Boolean isValidObjCObject = ((CFRuntimeBase *) cf)->_cfisa != 0;
+           Boolean isValidObjCObject = false;
+           if (((CFRuntimeBase *) cf)->_cfisa) {
+               Class class = object_getClass(cf);
+               isValidObjCObject = !_class_isFutureClass(class);
+           }
            if (isValidObjCObject) {
                if (__CFZombieEnabled) {
                    [(id)cf dealloc];
```

**Comment by facekapow** [comment]
~~@bugaevc That fix breaks LLDB *completely*. Can't attach to or run any process. Immediate segfault.~~ (this was for the old fix)

Yeah, the new fix works and doesn't cause any crashes (at least not in LLDB, trustd, or curl).

@LubosD Thanks, but I just extracted that into my Darling prefix (and Darling's `ls` says they're there) and got the same result.

**Comment by facekapow** [comment]
I think this might be an issue with my CoreCrypto implementation beacause the `ccrsa_eme_pkcs1v15_encode` function is failing. I'm going to fix it and hopefully that'll be it.

**Comment by facekapow** [comment]
Alright, I've *finally* got a solution. I decided to dive deeper into the certificate checking code and it seems that it expects a certificate bundle at `/System/Library/Security/Certificates.bundle`, which Darling doesn't have, so I copied it over from a real macOS installation and boom! It worked! It's pretty uncomfortable to ask Darling users to copy this over from a macOS installation, so we'd probably have to somehow build this bundle ourselves (because I'm pretty sure that legally we can't distribute it).

Before all that, actually, I had to fix my XPC unpacking code for doubles (I was using `xpc_uint64_create` instead of `xpc_double_create`; I'll push this update to my PR in a second). I also had to implement a few more missing functions in libxpc (I should open a separate PR for these, right?). I also had to fix my CoreCrypto code a bit.

With all that in place, curl says:
```
Darling [~]$ curl https://www.example.com
DARLING CRYPTO STUB: size_t ccec_x963_import_pub_size(size_t)
                                                             DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                                                                                                                       DARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                                          int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t): invalid public key size (expected 8728925506134605825 bytes; got 65)
                                                        DARLING CRYPTO STUB: size_t ccec_x963_import_pub_size(size_t)
                                                                                                                     DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                                          DARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                                                                                                  int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t): invalid public key size (expected 8728925506134605825 bytes; got 65)
                                                                                                                DARLING CRYPTO STUB:
size_t ccec_x963_import_pub_size(size_t)
                                        DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                                                                                                  DARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                     int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t): invalid public key size (expected 8728925506134605825 bytes; got 65)
                                   DARLING CRYPTO STUB: size_t ccec_x963_import_pub_size(size_t)
                                                                                                DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                     DARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                                                                             int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t): invalid public key size (expected 8728925506134605825 bytes; got 65)
                                                                                           DARLING CRYPTO STUB: size_t ccec_x963_import_pub_size(size_t)
                   DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                                                                             DARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                                                                                                                                    int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t): invalid public key size (expected 8728925506134605825 bytes; got 65)
             DARLING CRYPTO STUB: size_t ccec_x963_import_pub_size(size_t)
                                                                          DARLING CRYPTO STUB: int ccec_keysize_is_supported(size_t)
                                                                                                                                    D
ARLING CRYPTO STUB: ccec_const_cp_t ccec_get_cp(size_t)
                                                       int ccec_import_pub(ccec_const_cp_t, size_t, const uint8_t *, ccec_pub_ctx_t):
 invalid public key size (expected 8728925506134605825 bytes; got 65)
                                                                     <!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-
serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

So I think its obvious that I have a couple more functions to implement, but at least now curl is working, certificate checking and all!

I'm think it's a complete fluke that `https://www.example.com` works without having the other functions implemented, because all other URLs I try fail. Hopefully they'll work after I implement the necessary functions in CoreCrypto.

**Comment by ahyattdev** [comment]
@facekapow perhaps we can copy the Linux root CAs in /etc/ssl into that directory you found upon prefix creation/update. Doing it this way will prevent us from having to maintain our own trusted certs.

**Comment by facekapow** [comment]
We could use those to generate the bundle (i.e. copy them into the bundle), but we have to generate the bundle ourselves somehow, because it's in Apple's own bundle format (the same one they use for `.app`s).

**Comment by facekapow** [comment]
*sigh*:

```
Darling [~]$ curl https://www.example.com
curl: (35) SSL certificate problem: Couldn't understand the server certificate format
```
After updating to the latest master (and including my changes to CoreCrypto, libxpc, and libtrace), curl now errors out with this. This is happening even before any CoreCrypto or libxpc code is reached. I'm currently debugging to see where it's coming from (and I tried removing the keychains @LubosD provided, just in case, but nothing). Initial debugging looks like it's coming from the certificate not having a valid `_keychain_item`.

**Comment by facekapow** [comment]
That issue has been resolved; it's an issue in the current `darling-security` master, not this PR.

I've implemented the missing CoreCrypto functions, and now `https://www.example.com` works without any issue! Unfortunately, all other websites (the ones I tested: apple.com, github.com, microsoft.com) don't work (well, they work with `-k`, but that's what we're trying to avoid here).

**Comment by facekapow** [comment]
The new issue seems to be in websites that have HTTPS certificates with EV (extended validation) CAs. https://www.example.com doesn't have EV and neither do https://www.httpvshttps.com or https://www.google.com, and they work perfectly with curl, with and without `-k`. https://github.com and https://www.apple.com have EV CAs, so they return the "invalid certificate chain" error if `-k` is not used.

https://www.microsoft.com seems not to have an EV CA, but it just hangs with curl, regardless of whether `-k` is used or not. Looks like another bug; I'll get to it later after fixing EV CAs.

**Comment by ahyattdev** [comment]
Great progress so far! If github.com and brew.sh start working then we can get Homebrew going :wink:

**Pull request merged**
